let password = sessionStorage.getItem("chocita-admin-password") || "";
let photos = [];
const login = document.querySelector("#login"), manager = document.querySelector("#manager"), list = document.querySelector("#gallery-list");
function authHeaders(json = false) { const headers = { "X-Admin-Password": password }; if (json) headers["Content-Type"] = "application/json"; return headers; }
async function request(url, options = {}) { const isJson = options.body && !(options.body instanceof FormData); const response = await fetch(url, { ...options, headers: { ...authHeaders(isJson), ...(options.headers || {}) } }); if (!response.ok) { const body = await response.json().catch(() => ({})); throw new Error(body.error || "No se pudo guardar el cambio."); } return response.json(); }
function photoUrl(photo) { return photo.url || `/media/${photo.key}`; }
function render() { list.innerHTML = ""; photos.forEach((photo, index) => { const card = document.createElement("article"), active = photo.active !== false; card.className = `photo${active ? "" : " inactive"}`; card.innerHTML = `<img src="${photoUrl(photo)}" alt=""><div class="photo-actions"><button class="up" aria-label="Subir foto">↑</button><button class="down" aria-label="Bajar foto">↓</button><button class="toggle"></button></div><div class="photo-name"></div>`; card.querySelector(".photo-name").textContent = `${photo.alt || "Foto"}${active ? "" : " · Desactivada"}`; const up = card.querySelector(".up"), down = card.querySelector(".down"), toggle = card.querySelector(".toggle"); up.disabled = index === 0; down.disabled = index === photos.length - 1; toggle.textContent = active ? "Desactivar" : "Reactivar"; up.onclick = () => move(index, -1); down.onclick = () => move(index, 1); toggle.onclick = () => setActive(photo, !active); list.append(card); }); }
async function move(index, direction) { [photos[index], photos[index + direction]] = [photos[index + direction], photos[index]]; render(); try { await request("/api/admin/gallery", { method: "PUT", body: JSON.stringify({ photos }) }); } catch (error) { alert(error.message); await load(); } }
async function setActive(photo, active) { try { photos = (await request("/api/admin/photo", { method: "PATCH", body: JSON.stringify({ id: photo.id, active }) })).photos; render(); } catch (error) { alert(error.message); } }
async function load() { photos = (await request("/api/admin/gallery")).photos; render(); }
document.querySelector("#login-form").addEventListener("submit", async (event) => { event.preventDefault(); password = document.querySelector("#password").value; try { await load(); sessionStorage.setItem("chocita-admin-password", password); login.hidden = true; manager.hidden = false; } catch (error) { document.querySelector("#login-error").textContent = error.message; } });
document.querySelector("#photos-input").addEventListener("change", async (event) => { const status = document.querySelector("#upload-status"), files = [...event.target.files]; for (let i = 0; i < files.length; i += 1) { status.textContent = `Subiendo ${i + 1} de ${files.length}…`; const form = new FormData(); form.append("photo", files[i]); try { photos = (await request("/api/admin/upload", { method: "POST", body: form })).photos; render(); } catch (error) { status.textContent = error.message; return; } } event.target.value = ""; status.textContent = files.length ? "Fotos publicadas." : ""; });
if (password) { document.querySelector("#password").value = password; document.querySelector("#login-form").requestSubmit(); }
